### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by dvuiodvojd** [Kamppix/QuotaScalingMoons#1]
it's not a issue, i just wanted to suggest something
can you add a config to make the moons have value? i think it's too easy when its all free, you can disable if by default
:D

**Comment by Kamppix** [comment]
Hi, and thanks for the issue!

All moons' scrap values are currently adjusted based on the average scrap value of that moon and the current quota, meaning that the value you get from an Artifice run _should_ be the same as that from Experimentation. Regardless, the config option to use normal moon entry prices was added in v0.1.1. You just need to set `EnableFreeMoons` to `false`.

If I misunderstood you, and you had another type of idea for the pricing of moons, please do tell me more. I haven't done enough playtesting myself to tell if it should be changed in some way. But the idea behind the mod is to make every moon a viable option for endgame, meaning that no moon should be better than the others. I know it's not quite there yet, but that is the ultimate goal.

**Comment by dvuiodvojd** [comment]
Yes, that's right, sorry, I didn't see that it had already been added to the mod :D
And, I loved the mod, I wanted a mod that added this mechanic to the endgame for a long time.
Let me just ask you a question, can you help me configure it so I don't have so many scraps on the moons?
It's like, I just wanted the scrap value to increase, it's just that my PC isn't that good, and with the mod it's like 150+ scrap in the save I have (I have 20k+ quota)
I don't know if there is any way to do this so I wanted to ask you

**Comment by Kamppix** [comment]
Considering that I made this just for playing with my friends, I'm very glad to hear that someone else is also interested in, and enjoying this type of mod! :)

Now, to answer your question... If you were to change HQ (High Quota) `MinScrap` and `MaxScrap` to be lower, for example 12 and 16, it would *slow down* the scrap amount scaling. If you want the amount to stay the same for the rest of your run, you would have to set FQ (First Quota) `MinScrap` and `MaxScrap` to the same values as in HQ (26 and 31 by default, but you can choose any value).

That actually gives me a new config idea. I should make checkboxes for having the HQ values be the upper limit. It would be especially helpful with the scrap amount, since that is just kind of pointless to scale past a certain point.

**Comment by dvuiodvojd** [comment]
OK thanks!
If you can do what you said I would be very happy, it would help a lot XD
i hope its not too hard to make

**Comment by Kamppix** [comment]
Just uploaded 0.2.3 to Thunderstore, adding the limiter checkboxes. It usually takes 60+ minutes to show up on r2modman, but you can now manually install the new version. :)

**Comment by Kamppix** [comment]
Based Lain fan btw o7
